language: csharp
solution: com.papapoi.ReceiverMeow/Native.sln
before_deploy:
  - sudo apt-get install p7zip-full
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
  - receiver-meow.7z
  skip_cleanup: true
  on:
    tags: true
